### ISSUE TITLE
Ошибка 64x-битной библиотеки glibc\lib32z1

### ISSUE THREAD

**Issue by TheMrMes109** [alexeylesin/pterodactyl-eggs#1]
При билде лаунчера KeeperJerry в EXE выдает ошибку
java.io.IOException: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/container/libraries/launch4j/bin/windres": error=2, No such file or directory

На обычном Debian без Докера фиксилось через 
sudo apt-get update
sudo apt-get install lib32z1

Как добавить библиотеку glibc\lib32z1 в "Докер" или "Скрипт" запуска ?

**Comment by TheMrMes109** [comment]
2020.11.21 02:23:58 [INFO] Command 'build'
2020.11.21 02:23:58 [INFO] Building launcher binary file
2020.11.21 02:23:59 [INFO] Building launcher EXE binary file (Using Launch4J)
2020.11.21 02:23:59 [WARN] Missing favicon.ico file
2020.11.21 02:23:59 [INFO]  Compiling resources
2020.11.21 02:23:59 [INFO]  Generated resource file...

2020.11.21 02:23:59 [INFO]  LANGUAGE 0, 1
1 VERSIONINFO
FILEVERSION 1, 0, 0, 0
PRODUCTVERSION 1, 0, 0, 0
FILEFLAGSMASK 0
FILEOS 0x40000
FILETYPE 1
{
 BLOCK "StringFileInfo"
 {
  BLOCK "040904E4"
  {
   VALUE "CompanyName", ""
   VALUE "FileDescription", "KeeperJerry's Launcher"
   VALUE "FileVersion", "1.6.0, build 1.6.0, 17.09.2020"
   VALUE "InternalName", "Launcher"
   VALUE "LegalCopyright", "© KeeperJerry & sashok724 LLC"
   VALUE "LegalTrademarks", "This product is licensed under WTFPL 2.0"
   VALUE "OriginalFilename", "BWS.exe"
   VALUE "ProductName", "KeeperJerry's Launcher"
   VALUE "ProductVersion", "1.6.0, build 1.6.0, 17.09.2020"
  }
 }
BLOCK "VarFileInfo"
{
VALUE "Translation", 0x0409, 0x04E4
}
}2 RCDATA BEGIN "1.8.0\0" END
18 RCDATA BEGIN "1\0" END
30 RCDATA BEGIN "2\0" END
10 RCDATA BEGIN "JVM Error\0" END
21 RCDATA BEGIN "http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html\0" END
8 RCDATA BEGIN ".\0" END
20 RCDATA BEGIN "32\0" END
101 RCDATA BEGIN "An error occurred while starting the application.\0" END
102 RCDATA BEGIN "This application was configured to use a bundled Java Runtime Environment but the runtime is missing or corrupted.\0" END
103 RCDATA BEGIN "This application requires a Java Runtime Environment\0" END
104 RCDATA BEGIN "The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.\0" END
17 RCDATA BEGIN "true\0" END

2020.11.21 02:23:59 [ERROR] java.io.IOException: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/container/libraries/launch4j/bin/windres": error=2, No such file or directory

**Comment by alexeylesin** [comment]
Внесены изменения в [Dockerfile](https://github.com/alexeylesin/pterodactyl-core/blob/master/java-11/Dockerfile), проблема должна быть исправлена.
